### ISSUE TITLE
Cannot find module 'postcss'

### ISSUE THREAD

**Issue by Itrulia** [OEvgeny/postcss-atroot#3]

**Comment by OEvgeny** [comment]
How do you run into this problem?

**Comment by Itrulia** [comment]
The dependency is specified as a dev-dependency (it is not). After npm install with node v5.0.0 the dependency was not installed, because it was specified as dev-dependency.

If I change it to a normal dependency it works. I think node changed something about dependencies with a recent version, had some deprecation warning weeks before about dev-dependency and dependency.

**Comment by OEvgeny** [comment]
@Itrulia I'm not sure that we must add `postcss` as a dependency. But leaving it in `devDependencies` also looks bad to me. 
Should we add it to `peerDependencies` instead? Can you test this and update PR if it works well?

**Comment by OEvgeny** [comment]
So, it's not needed now. See related discussion.

Thanks for contribution!
